# Generated by Django 4.2.2 on 2026-04-09 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hallfacility',
            unique_together={('hall', 'facility')},
        ),
        migrations.AlterUniqueTogether(
            name='hallbookmark',
            unique_together={('user', 'hall')},
        ),
    ]
