# Generated by Django 4.2.2 on 2026-04-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='hall.hall')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
