# Generated by Django 6.0.4 on 2026-06-23 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_hallimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='owner_department',
            field=models.CharField(blank=True, choices=[('VENTURES', 'Ventures'), ('FACILITY', 'Facility')], help_text='Department responsible for operational management', max_length=30),
        ),
        migrations.AddField(
            model_name='hall',
            name='rules',
            field=models.TextField(blank=True, help_text='Usage rules and terms displayed to applicants before booking'),
        ),
        migrations.AddField(
            model_name='hall',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions for booking this hall'),
        ),
        migrations.CreateModel(
            name='HallBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hall.hall')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
