# Generated by Django 6.0.4 on 2026-06-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_hall_owner_department_hall_rules_hall_terms_and_more'),
        ('reservations', '0007_remove_reservation_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hallfacility',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hallfacility',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='hallfacility',
            name='hall',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='price_per_hour',
            new_name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='hall_type',
        ),
        migrations.AddField(
            model_name='hall',
            name='category',
            field=models.CharField(choices=[('LECTURE', 'Lecture Hall'), ('CONFERENCE', 'Conference Hall'), ('SEMINAR', 'Seminar Room'), ('SOCIAL_EVENT', 'Social Event Hall'), ('MULTIPURPOSE', 'Multipurpose Hall'), ('OUTDOOR', 'Outdoor Space')], default='MULTIPURPOSE', max_length=30),
        ),
        migrations.AddField(
            model_name='hall',
            name='extra_hour_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hall',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='HallAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.amenity')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hall.hall')),
            ],
            options={
                'verbose_name_plural': 'Hall Amenities',
                'unique_together': {('hall', 'amenity')},
            },
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='HallFacility',
        ),
    ]
