# Generated by Django 6.0.4 on 2026-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_amenity_remove_hallfacility_facility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallimage',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='hallimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
