# Generated by Django 6.0.4 on 2026-06-24 10:47

from django.db import migrations


def move_images(apps, schema_editor):
    Hall = apps.get_model("hall", "Hall")
    HallImage = apps.get_model("hall", "HallImage")
    
    for hall in Hall.objects.exclude(image="").exclude(image__isnull=True):
        # Create a HallImage with order 0 and the same image path
        HallImage.objects.create(
            hall=hall,
            image=hall.image,
            order=0
        )

def reverse_images(apps, schema_editor):
    pass  # We don't need to move them back; if reversed, the old image field remains but is blank for new records.


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_alter_hallimage_options_hallimage_order'),
    ]

    operations = [
        migrations.RunPython(move_images, reverse_images),
    ]
