# Generated by Django 6.0.4 on 2026-06-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0007_move_hall_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='image',
        ),
    ]
