# Generated by Django 6.0.4 on 2026-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_remove_hall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, default='bi-star', help_text='Bootstrap icon class, e.g. bi-wifi, bi-projector, bi-soundwave', max_length=100),
        ),
    ]
