# Generated by Django 6.0.4 on 2026-06-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_amenity_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallimage',
            options={'ordering': ['display_order', '-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='hallimage',
            old_name='order',
            new_name='display_order',
        ),
        migrations.AddField(
            model_name='hall',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived halls are hidden from public listing and require admin to restore.'),
        ),
        migrations.AddField(
            model_name='hall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hallimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Only one image per hall can be the cover. Setting this removes cover from all others.'),
        ),
    ]
