# Generated by Django 6.0.4 on 2026-07-06 14:37

import hall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0010_cover_image_archive_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(upload_to=hall.models.hall_image_path),
        ),
    ]
