# Generated by Django 6.0.4 on 2026-07-06 16:17

import hall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0011_alter_hallimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=hall.models.hall_image_path),
        ),
    ]
