# Generated by Django 6.0.4 on 2026-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('icon', models.CharField(blank=True, default='bi-star', help_text='Bootstrap icon class, e.g. bi-wifi, bi-projector', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='announcements/attachments/'),
        ),
    ]
