# Generated by Django 6.0.4 on 2026-06-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_amenity_announcement_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
