# Generated by Django 6.0.4 on 2026-07-05 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_announcement_category_announcement_unique_view_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '2025/2026 Session' or 'Second Semester 2025'", max_length=100)),
                ('period_type', models.CharField(choices=[('SESSION', 'Academic Session'), ('SEMESTER', 'Semester')], default='SESSION', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Mark the active period for default filter selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='affected_module',
            field=models.CharField(blank=True, help_text='App/module where action occurred', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, help_text='Browser used by the actor', max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional context or comments'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='department',
            field=models.CharField(blank=True, help_text='Department of the acting user', max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='os_info',
            field=models.CharField(blank=True, help_text='Operating system of the actor', max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the action if provided'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, help_text='Unique ID for the HTTP request', max_length=64),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'timestamp'], name='core_auditl_model_n_078933_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['affected_module', 'timestamp'], name='core_auditl_affecte_9e3495_idx'),
        ),
    ]
