# Generated by Django 6.0.4 on 2026-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expand_auditlog_academic_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', max_length=500, null=True, upload_to='announcements/attachments/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='announcements/images/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='announcements/videos/'),
        ),
    ]
