# Generated by Django 4.2.2 on 2026-04-09 09:06

from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(choices=[('LECTURE', 'Lecture'), ('EXAM', 'Exam'), ('EVENT', 'Event'), ('MEETING', 'Meeting')], max_length=20)),
                ('attendees_count', models.PositiveIntegerField(default=0)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_type', models.CharField(choices=[('MINUTE', 'Minute'), ('HOUR', 'Hour'), ('DAY', 'Day')], default='HOUR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=12)),
                ('booking_reference', models.CharField(default=reservations.models._generate_reference, editable=False, max_length=40, unique=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hall.hall')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_booking_time', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hall.facility')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_facilities', to='reservations.reservation')),
            ],
        ),
    ]
