# Generated by Django 4.2.2 on 2026-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='is_forgiven',
            field=models.BooleanField(default=False),
        ),
    ]
