# Generated by Django 4.2.2 on 2026-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_damagereport_is_forgiven'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
