# Generated by Django 6.0.4 on 2026-06-23 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_coupon_reservation_discount_amount_penalty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allowed_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_faculty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_hall_ids',
            field=models.TextField(blank=True, help_text='Comma-separated hall IDs'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_roles',
            field=models.CharField(blank=True, help_text='Comma-separated roles, e.g. STUDENT,STAFF', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_cap',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 means no cap', max_digits=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_booking_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited per user'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes from the applicant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='purpose',
            field=models.CharField(choices=[('LECTURE', 'Lecture/Academic'), ('EXAM', 'Examination'), ('EVENT', 'Social/Cultural'), ('MEETING', 'Meeting/Conference'), ('WORKSHOP', 'Workshop/Training'), ('GRADUATION', 'Graduation/Convocation'), ('RELIGIOUS', 'Religious Programme'), ('SPORTS', 'Sports/Recreation'), ('EXHIBITION', 'Exhibition/Fair'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('FORWARDED', 'Forwarded'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected'), ('AVAILABLE', 'Available'), ('APPROVED_PAYMENT', 'Approved for Payment'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('INSPECTION_PENDING', 'Inspection Pending'), ('DAMAGE_REPORTED', 'Damage Reported'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HallInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('DAMAGE_REPORTED', 'Damage Reported')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_staff_note', models.BooleanField(default=False, help_text='Internal notes not visible to applicants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reservations.reservation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AUTHORIZATION_LETTER', 'Authorization Letter'), ('PERMIT', 'Permit'), ('IMAGE', 'Image'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='reservations/documents/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reservations.reservation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', 'version'],
                'unique_together': {('reservation', 'document_type', 'version')},
            },
        ),
    ]
