# Generated by Django 6.0.4 on 2026-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_coupon_allowed_department_coupon_allowed_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='coupon',
        ),
        migrations.AlterUniqueTogether(
            name='reservationfacility',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservationfacility',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='reservationfacility',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='duration_type',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost determined by Ventures', max_digits=12),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='ReservationFacility',
        ),
    ]
