# Generated by Django 6.0.4 on 2026-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_amount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='original_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total before discounts', max_digits=12),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final cost after discount determined by Ventures', max_digits=12),
        ),
    ]
