# Generated by Django 6.0.4 on 2026-06-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_amenity_icon'),
        ('reservations', '0008_reservation_coupon_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='coupon_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when applicant requested this coupon', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of coupon data at request time for audit trail'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified')], help_text='Ventures decision on the coupon request', max_length=20),
        ),
        migrations.CreateModel(
            name='InternalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_department', models.CharField(help_text='Department or unit requesting the hall', max_length=200)),
                ('event_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('LECTURE', 'Lecture/Academic'), ('EXAM', 'Examination'), ('EVENT', 'Social/Cultural'), ('MEETING', 'Meeting/Conference'), ('WORKSHOP', 'Workshop/Training'), ('GRADUATION', 'Graduation/Convocation'), ('RELIGIOUS', 'Religious Programme'), ('SPORTS', 'Sports/Recreation'), ('EXHIBITION', 'Exhibition/Fair'), ('OTHER', 'Other')], max_length=30)),
                ('organizer_name', models.CharField(blank=True, help_text='Name of the event organizer', max_length=200)),
                ('organizer_phone', models.CharField(blank=True, max_length=30)),
                ('attendees_count', models.PositiveIntegerField(default=0)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Marks recurring departmental events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_reservations', to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_reservations', to='hall.hall')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
                'indexes': [models.Index(fields=['hall', 'booking_date'], name='reservation_hall_id_a3375e_idx'), models.Index(fields=['status'], name='reservation_status_88205f_idx')],
            },
        ),
    ]
