# Generated by Django 6.0.4 on 2026-06-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_add_internal_reservation_and_coupon_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmessage',
            name='read_by_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationmessage',
            name='read_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
