# Generated by Django 6.0.4 on 2026-06-25 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0010_cover_image_archive_audit'),
        ('reservations', '0010_reservationmessage_read_by_applicant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_SUBMITTED', 'Booking Submitted'), ('VENTURES_REVIEW_STARTED', 'Ventures Review Started'), ('FORWARDED_TO_FACILITY', 'Forwarded to Facility'), ('FACILITY_APPROVED', 'Facility Approved'), ('FACILITY_REJECTED', 'Facility Rejected'), ('RETURNED_TO_VENTURES', 'Returned to Ventures'), ('COUPON_REVIEWED', 'Coupon Reviewed'), ('BILLING_CONFIRMED', 'Billing Confirmed'), ('PAYMENT_REQUESTED', 'Payment Requested'), ('PAYMENT_PROOF_UPLOADED', 'Payment Proof Uploaded'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('PERMIT_GENERATED', 'Booking Permit Generated'), ('EVENT_COMPLETED', 'Event Completed'), ('INSPECTION_OPENED', 'Post-Event Inspection Opened'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('DAMAGE_ASSESSED', 'Damage Assessed'), ('DAMAGE_INVOICE_ISSUED', 'Damage Invoice Issued'), ('DAMAGE_PAYMENT_UPLOADED', 'Damage Payment Proof Uploaded'), ('DAMAGE_PAYMENT_VERIFIED', 'Damage Payment Verified'), ('LIABILITY_FORGIVEN', 'Liability Forgiven'), ('CASE_CLOSED', 'Case Closed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('MESSAGE_SENT', 'Message Sent'), ('NOTE_ADDED', 'Note Added'), ('STATUS_OVERRIDE', 'Status Override (Admin)'), ('RESTRICTION_REMOVED', 'Restriction Removed'), ('INFORMATION_REQUESTED', 'Information Requested')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reservations/damage_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reservations/damage_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_condition', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('cleanliness', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('furniture_status', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('equipment_status', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('damage_found', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('NO_DAMAGE', 'No Damage — Clear'), ('DAMAGE_FOUND', 'Damage Found')], max_length=20)),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reservations/inspection_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reservations/thread_attachments/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('APPLICANT_VISIBLE', 'Applicant Visible'), ('INTERNAL', 'Internal Management'), ('SYSTEM_GENERATED', 'System Generated')], default='APPLICANT_VISIBLE', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff_note', models.BooleanField(default=False, help_text='True when message_type=INTERNAL (legacy compat)')),
                ('read_by_applicant', models.BooleanField(default=False)),
                ('read_by_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='damagereport',
            name='admin_waiver_reason',
            field=models.TextField(blank=True, help_text='Reason for admin forgiveness/waiver'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='affected_items',
            field=models.TextField(blank=True, help_text='List of items damaged'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='assessment_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='cost_estimate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Formal assessment cost estimate', max_digits=12),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_waivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_permit_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='case_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_VENTURES_REVIEW', 'Under Ventures Review'), ('UNDER_FACILITY_REVIEW', 'Under Facility Review'), ('FACILITY_APPROVED', 'Facility Approved'), ('FACILITY_REJECTED', 'Facility Rejected'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('UNDER_BURSARY_VERIFICATION', 'Under Bursary Verification'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('AWAITING_FINAL_APPROVAL', 'Awaiting Final Approval'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('EVENT_COMPLETED', 'Event Completed'), ('UNDER_POST_EVENT_INSPECTION', 'Under Post-Event Inspection'), ('DAMAGE_ASSESSED', 'Damage Assessed'), ('AWAITING_DAMAGE_PAYMENT', 'Awaiting Damage Payment'), ('DAMAGE_PAYMENT_SUBMITTED', 'Damage Payment Submitted'), ('UNDER_DAMAGE_PAYMENT_VERIFICATION', 'Under Damage Payment Verification'), ('DAMAGE_PAYMENT_VERIFIED', 'Damage Payment Verified'), ('CASE_CLOSED', 'Case Closed'), ('USER_RESTRICTED', 'User Restricted')], db_index=True, default='SUBMITTED', help_text='Primary managed booking lifecycle status', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_approval_notes',
            field=models.TextField(blank=True, help_text='Ventures notes on coupon decision'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of coupon discount value', max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_rules_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Full coupon rules at time of application'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_type',
            field=models.CharField(blank=True, help_text='Coupon type snapshot', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='qr_verification_code',
            field=models.UUIDField(blank=True, editable=False, help_text='Generated on BOOKING_APPROVED', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='new_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='previous_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated repair/replacement cost', max_digits=12),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('FORWARDED', 'Forwarded'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected'), ('AVAILABLE', 'Available'), ('APPROVED_PAYMENT', 'Approved for Payment'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('INSPECTION_PENDING', 'Inspection Pending'), ('DAMAGE_REPORTED', 'Damage Reported'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservationdocument',
            name='document_type',
            field=models.CharField(choices=[('AUTHORIZATION_LETTER', 'Authorization Letter'), ('PERMIT', 'Permit'), ('IMAGE', 'Image'), ('PAYMENT_PROOF', 'Payment Proof'), ('DAMAGE_PROOF', 'Damage Payment Proof'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['case_status'], name='reservation_case_st_289f59_idx'),
        ),
        migrations.AddField(
            model_name='bookingtimeline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtimeline',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='damagedocument',
            name='damage_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='reservations.damagereport'),
        ),
        migrations.AddField(
            model_name='damagedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagephoto',
            name='damage_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reservations.damagereport'),
        ),
        migrations.AddField(
            model_name='damagephoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hallinspectionreport',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hallinspectionreport',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='inspectionphoto',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reservations.hallinspectionreport'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='reservations.threadmessage'),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reservations.communicationthread'),
        ),
        migrations.AddField(
            model_name='threadattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reservations.threadmessage'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='reservations.threadmessage'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
