# Generated by Django 6.0.4 on 2026-06-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_add_reservation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='target_roles',
            field=models.CharField(blank=True, help_text="Comma-separated list of roles allowed to view this message (e.g. 'VENTURES,BURSARY,APPLICANT').", max_length=255),
        ),
    ]
