# Generated by Django 6.0.4 on 2026-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_threadmessage_target_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdocument',
            name='visible_to',
            field=models.CharField(blank=True, default='VENTURES', help_text='Comma-separated list of staff roles that can view this document. Valid values: VENTURES, BURSARY. Facility is excluded from document routing.', max_length=100),
        ),
    ]
