# Generated by Django 6.0.4 on 2026-06-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_add_document_visible_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdocument',
            name='visible_to',
            field=models.CharField(blank=True, default='VENTURES', help_text='Comma-separated list of roles that can view this document. Valid values: APPLICANT, FACILITY, VENTURES, BURSARY.', max_length=100),
        ),
    ]
