# Generated by Django 6.0.4 on 2026-06-28 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_update_document_visible_to_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtimeline',
            name='event_type',
            field=models.CharField(choices=[('BOOKING_SUBMITTED', 'Booking Submitted'), ('VENTURES_REVIEW_STARTED', 'Ventures Review Started'), ('FORWARDED_TO_FACILITY', 'Forwarded to Facility'), ('FACILITY_APPROVED', 'Facility Approved'), ('FACILITY_REJECTED', 'Facility Rejected'), ('RETURNED_TO_VENTURES', 'Returned to Ventures'), ('COUPON_REVIEWED', 'Coupon Reviewed'), ('COUPON_ACTION', 'Coupon Action'), ('BILLING_CONFIRMED', 'Billing Confirmed'), ('PAYMENT_AUTHORIZATION_OPENED', 'Payment Authorization Opened'), ('PAYMENT_AUTHORIZATION_SUBMITTED', 'Payment Authorization Submitted'), ('PAYMENT_DEADLINE_SET', 'Payment Deadline Set'), ('PAYMENT_DEADLINE_EXTENDED', 'Payment Deadline Extended'), ('PAYMENT_DEADLINE_EXPIRED', 'Payment Deadline Expired'), ('PAYMENT_REQUESTED', 'Payment Requested'), ('PAYMENT_PROOF_UPLOADED', 'Payment Proof Uploaded'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('PERMIT_GENERATED', 'Booking Permit Generated'), ('EVENT_COMPLETED', 'Event Completed'), ('INSPECTION_OPENED', 'Post-Event Inspection Opened'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('INSPECTION_REMINDER_SENT', 'Inspection Reminder Sent'), ('DAMAGE_ASSESSED', 'Damage Assessed'), ('DAMAGE_INVOICE_ISSUED', 'Damage Invoice Issued'), ('DAMAGE_PAYMENT_UPLOADED', 'Damage Payment Proof Uploaded'), ('DAMAGE_PAYMENT_VERIFIED', 'Damage Payment Verified'), ('LIABILITY_FORGIVEN', 'Liability Forgiven'), ('PENALTY_CREATED', 'Penalty Created'), ('PENALTY_UPDATED', 'Penalty Updated'), ('CASE_CLOSED', 'Case Closed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('MESSAGE_SENT', 'Message Sent'), ('NOTE_ADDED', 'Note Added'), ('STATUS_OVERRIDE', 'Status Override (Admin)'), ('RESTRICTION_REMOVED', 'Restriction Removed'), ('INFORMATION_REQUESTED', 'Information Requested')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='case_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_VENTURES_REVIEW', 'Under Ventures Review'), ('UNDER_FACILITY_REVIEW', 'Under Facility Review'), ('FACILITY_APPROVED', 'Facility Approved'), ('FACILITY_REJECTED', 'Facility Rejected'), ('PAYMENT_AUTHORIZATION', 'Payment Authorization'), ('PAYMENT_EXPIRED', 'Payment Expired'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('UNDER_BURSARY_VERIFICATION', 'Under Bursary Verification'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('AWAITING_FINAL_APPROVAL', 'Awaiting Final Approval'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('EVENT_COMPLETED', 'Event Completed'), ('UNDER_POST_EVENT_INSPECTION', 'Under Post-Event Inspection'), ('DAMAGE_ASSESSED', 'Damage Assessed'), ('AWAITING_DAMAGE_PAYMENT', 'Awaiting Damage Payment'), ('DAMAGE_PAYMENT_SUBMITTED', 'Damage Payment Submitted'), ('UNDER_DAMAGE_PAYMENT_VERIFICATION', 'Under Damage Payment Verification'), ('DAMAGE_PAYMENT_VERIFIED', 'Damage Payment Verified'), ('CASE_CLOSED', 'Case Closed'), ('USER_RESTRICTED', 'User Restricted')], db_index=True, default='SUBMITTED', help_text='Primary managed booking lifecycle status', max_length=50),
        ),
        migrations.CreateModel(
            name='CouponActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPLACED', 'Replaced'), ('REMOVED', 'Removed'), ('APPLIED', 'Applied')], max_length=20)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('old_code', models.CharField(blank=True, help_text='Previous coupon code (on replace)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_action_logs', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('hall_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_charges_notes', models.CharField(blank=True, max_length=255)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='VAT percentage (e.g. 7.5 for 7.5%). Set 0 if not applicable.', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('coupon_action', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPLACED', 'Replaced'), ('REMOVED', 'Removed'), ('APPLIED', 'Applied')], max_length=20)),
                ('coupon_action_notes', models.TextField(blank=True)),
                ('coupon_action_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_type', models.CharField(choices=[('HOURS_24', '24 Hours'), ('HOURS_48', '48 Hours'), ('HOURS_72', '72 Hours'), ('CUSTOM', 'Custom Date & Time')], default='HOURS_48', max_length=20)),
                ('payment_deadline', models.DateTimeField(blank=True, help_text='Absolute datetime by which payment must be received.', null=True)),
                ('deadline_set_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_extended', models.BooleanField(default=False)),
                ('deadline_extension_count', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('ventures_notes', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_authorizations_created', to=settings.AUTH_USER_MODEL)),
                ('coupon_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_action_authorizations', to=settings.AUTH_USER_MODEL)),
                ('deadline_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_deadlines_set', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_authorization', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineExtensionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_deadline', models.DateTimeField(blank=True, null=True)),
                ('new_deadline', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('EXTENDED', 'Extended'), ('SHORTENED', 'Shortened'), ('REMOVED', 'Removed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_logs', to='reservations.paymentauthorization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenturesPenaltyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('PENALTY', 'Penalty'), ('ADMINISTRATIVE', 'Administrative Fee'), ('LATE_CHARGE', 'Late Charge'), ('ADDITIONAL', 'Additional Charge')], default='PENALTY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ventures_penalties', to=settings.AUTH_USER_MODEL)),
                ('penalty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ventures_record', to='reservations.penalty')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventures_penalty_records', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_number', models.PositiveIntegerField(default=1, help_text='1=immediate, 2=24h, 3=48h')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_roles', models.CharField(default='FACILITY', help_text='Comma-separated list of roles notified.', max_length=100)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reminders', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('reservation', 'reminder_number')},
            },
        ),
    ]
