# Generated by Django 6.0.4 on 2026-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_alter_bookingtimeline_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedocument',
            name='file',
            field=models.FileField(max_length=500, upload_to='reservations/damage_documents/'),
        ),
        migrations.AlterField(
            model_name='damagephoto',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='reservations/damage_photos/'),
        ),
        migrations.AlterField(
            model_name='inspectionphoto',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='reservations/inspection_photos/'),
        ),
        migrations.AlterField(
            model_name='reservationdocument',
            name='file',
            field=models.FileField(max_length=500, upload_to='reservations/documents/'),
        ),
        migrations.AlterField(
            model_name='threadattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to='reservations/thread_attachments/'),
        ),
    ]
