# Generated by Django 4.2.2 on 2026-04-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_coupon_reservation_discount_amount_penalty_and_more'),
        ('payments', '0004_payment_currency_payment_damage_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='reservations.penalty'),
        ),
    ]
