# Generated by Django 6.0.4 on 2026-06-24 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_remove_hall_image'),
        ('payments', '0005_payment_penalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applicable_categories', models.JSONField(blank=True, default=list)),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_per_user', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('faculty_restriction', models.CharField(blank=True, max_length=200)),
                ('department_restriction', models.CharField(blank=True, max_length=200)),
                ('role_restriction', models.CharField(blank=True, max_length=50)),
                ('is_stackable', models.BooleanField(default=False)),
                ('owner_department', models.CharField(blank=True, choices=[('VENTURES', 'Ventures'), ('FACILITY', 'Facility')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_halls', models.ManyToManyField(blank=True, related_name='coupons', to='hall.hall')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
