# Generated by Django 6.0.4 on 2026-06-25 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_coupon'),
        ('reservations', '0010_reservationmessage_read_by_applicant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(help_text='Scanned/photographed receipt or bank evidence', upload_to='payments/proofs/')),
                ('transaction_ref', models.CharField(blank=True, help_text='Bank/payment transaction reference number', max_length=120)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=0, help_text='Amount applicant claims to have paid', max_digits=12)),
                ('payment_type', models.CharField(choices=[('BOOKING', 'Booking Payment'), ('DAMAGE', 'Damage Payment')], default='BOOKING', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('bursary_notes', models.TextField(blank=True, help_text='Bursary verification notes')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='reservations.reservation')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
