# Generated by Django 6.0.4 on 2026-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='payment_type',
            field=models.CharField(choices=[('BOOKING', 'Booking Payment'), ('DAMAGE', 'Damage Payment'), ('PENALTY', 'Penalty Payment')], default='BOOKING', max_length=10),
        ),
    ]
