# Generated by Django 6.0.4 on 2026-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_paymentproof_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='receipt_file',
            field=models.FileField(help_text='Scanned/photographed receipt or bank evidence', max_length=500, upload_to='payments/proofs/'),
        ),
    ]
