# Generated by Django 6.0.4 on 2026-06-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_loginlog_rolecapability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecapability',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('EXTERNAL', 'External'), ('DEPARTMENT', 'Department'), ('VENTURES', 'Ventures'), ('FACILITY', 'Facility')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('EXTERNAL', 'External'), ('DEPARTMENT', 'Department'), ('VENTURES', 'Ventures'), ('FACILITY', 'Facility')], default='EXTERNAL', max_length=20),
        ),
    ]
