# Generated by Django 6.0.4 on 2026-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rolecapability_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecapability',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('EXTERNAL', 'External'), ('DEPARTMENT', 'Department'), ('VENTURES', 'Ventures'), ('FACILITY', 'Facility'), ('BURSARY', 'Bursary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('EXTERNAL', 'External'), ('DEPARTMENT', 'Department'), ('VENTURES', 'Ventures'), ('FACILITY', 'Facility'), ('BURSARY', 'Bursary')], default='EXTERNAL', max_length=20),
        ),
    ]
