# Generated by Django 6.0.4 on 2026-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_broadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to action or details', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to action or details', max_length=500, null=True),
        ),
    ]
