# Generated by Django 6.0.4 on 2026-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_broadcastmessage_link_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='broadcasts/attachments/'),
        ),
    ]
