# Generated by Django 6.0.4 on 2026-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_notification_type_notification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', max_length=500, null=True, upload_to='broadcasts/attachments/'),
        ),
    ]
